---
- name: Get Kernel Version
  hosts: 127.0.0.1
  tasks:
    - name: Execute uname command
      shell: uname -r
      register: kernel_version_output

    - name: Display Kernel Version
      debug:
        msg: "Kernel Version: {{ kernel_version_output.stdout }}"
